"""Generates the two charts for auditfinal.md. Not part of the Go project;
run once with `python3 make_charts.py` from this directory to (re)produce the
PNGs. Palette + mark specs follow the dataviz skill's reference palette."""

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# --- palette (reference instance, light mode) --------------------------------
SURFACE = "#fcfcfb"
INK_PRIMARY = "#0b0b0b"
INK_SECONDARY = "#52514e"
INK_MUTED = "#898781"
GRIDLINE = "#e1e0d9"
BASELINE = "#c3c2b7"
BLUE = "#2a78d6"   # categorical slot 1 -- "avant"
AQUA = "#1baf7a"   # categorical slot 3 -- "apres"

plt.rcParams.update({
    "font.family": "sans-serif",
    "font.sans-serif": ["Helvetica Neue", "Arial", "DejaVu Sans"],
    "text.color": INK_PRIMARY,
    "axes.edgecolor": BASELINE,
    "axes.labelcolor": INK_SECONDARY,
    "xtick.color": INK_MUTED,
    "ytick.color": INK_PRIMARY,
    "figure.facecolor": SURFACE,
    "axes.facecolor": SURFACE,
    "savefig.facecolor": SURFACE,
})

# CHART 1 (the 75/25 part-to-whole bar) was dropped: it only restated a
# number already given in the text as a stat callout, with no information a
# reader didn't already have. The flamegraph (a separate pprof artifact, not
# generated by this script) carries the visual evidence instead.

# ============================================================== CHART 2 ======
# Before/after wall-clock time, log scale, medium scenario, both optimizations.
fig, ax = plt.subplots(figsize=(7.5, 3.6), dpi=200)

rows = [
    ("Module principal — avant", 4100, BLUE),
    ("Module principal — après", 39.25, AQUA),
    ("Module « scent » — avant", 3852, BLUE),
    ("Module « scent » — après", 42.26, AQUA),
]
labels = [r[0] for r in rows]
values = [r[1] for r in rows]
colors = [r[2] for r in rows]
y = list(range(len(rows)))[::-1]

ax.barh(y, values, height=0.55, color=colors, zorder=3)

for yi, v in zip(y, values):
    txt = f"{v:,.0f} ms" if v >= 100 else f"{v:.1f} ms"
    ax.text(v * 1.18, yi, txt, va="center", ha="left",
             color=INK_PRIMARY, fontsize=10.5, fontweight="medium")

ax.set_yticks(y)
ax.set_yticklabels(labels, fontsize=10.5, color=INK_PRIMARY)
ax.set_xscale("log")
ax.set_xlim(10, 20000)
ax.set_xlabel("Temps d'exécution (millisecondes, échelle logarithmique)",
               fontsize=9.5, color=INK_SECONDARY)
ax.xaxis.grid(True, which="major", color=GRIDLINE, linewidth=1, zorder=0)
ax.set_axisbelow(True)
for spine in ["top", "right", "left"]:
    ax.spines[spine].set_visible(False)
ax.spines["bottom"].set_color(BASELINE)
ax.tick_params(axis="x", labelsize=9, colors=INK_MUTED)
ax.tick_params(axis="y", length=0)

legend_handles = [
    plt.Rectangle((0, 0), 1, 1, color=BLUE, label="Avant optimisation"),
    plt.Rectangle((0, 0), 1, 1, color=AQUA, label="Après optimisation"),
]
ax.legend(handles=legend_handles, loc="lower right", frameon=False,
          fontsize=9.5, labelcolor=INK_SECONDARY)

fig.tight_layout()
fig.savefig("results.png", bbox_inches="tight")
plt.close(fig)

# ============================================================== CHART 3 ======
# Before/after allocation count, log scale, medium scenario, both modules.
fig, ax = plt.subplots(figsize=(7.5, 3.6), dpi=200)

rows3 = [
    ("Module principal — avant", 66_302_084, BLUE),
    ("Module principal — après", 165_315, AQUA),
    ("Module « scent » — avant", 67_087_966, BLUE),
    ("Module « scent » — après", 164_729, AQUA),
]
labels3 = [r[0] for r in rows3]
values3 = [r[1] for r in rows3]
colors3 = [r[2] for r in rows3]
y3 = list(range(len(rows3)))[::-1]

ax.barh(y3, values3, height=0.55, color=colors3, zorder=3)

for yi, v in zip(y3, values3):
    txt = f"{v/1_000_000:.1f} M" if v >= 1_000_000 else f"{v/1_000:.0f} k"
    ax.text(v * 1.18, yi, txt, va="center", ha="left",
             color=INK_PRIMARY, fontsize=10.5, fontweight="medium")

ax.set_yticks(y3)
ax.set_yticklabels(labels3, fontsize=10.5, color=INK_PRIMARY)
ax.set_xscale("log")
ax.set_xlim(50_000, 300_000_000)
ax.set_xlabel("Opérations mémoire par exécution (échelle logarithmique)",
               fontsize=9.5, color=INK_SECONDARY)
ax.xaxis.grid(True, which="major", color=GRIDLINE, linewidth=1, zorder=0)
ax.set_axisbelow(True)
for spine in ["top", "right", "left"]:
    ax.spines[spine].set_visible(False)
ax.spines["bottom"].set_color(BASELINE)
ax.tick_params(axis="x", labelsize=9, colors=INK_MUTED)
ax.tick_params(axis="y", length=0)

ax.legend(handles=legend_handles, loc="lower right", frameon=False,
          fontsize=9.5, labelcolor=INK_SECONDARY)

fig.tight_layout()
fig.savefig("allocations.png", bbox_inches="tight")
plt.close(fig)

# ============================================================== CHART 4 ======
# Full picture: all 4 registered engines, medium scenario, sec/op, log scale.
# Included for completeness (annex) -- gradient is a separate feature variant,
# not one of the two optimizations this report covers, shown here as-is.
fig, ax = plt.subplots(figsize=(8.3, 2.8), dpi=200)

rows4 = [
    ("naive (module principal, non corrigé)", 4100, BLUE),
    ("gradient (variante « retour au nid », non corrigée)", 3872, BLUE),
    ("scent (module « recherche de nourriture », corrigé)", 42.26, AQUA),
    ("flatgrid (module principal, corrigé)", 39.25, AQUA),
]
labels4 = [r[0] for r in rows4]
values4 = [r[1] for r in rows4]
colors4 = [r[2] for r in rows4]
y4 = list(range(len(rows4)))[::-1]

ax.barh(y4, values4, height=0.55, color=colors4, zorder=3)
for yi, v in zip(y4, values4):
    txt = f"{v:,.0f} ms" if v >= 100 else f"{v:.1f} ms"
    ax.text(v * 1.18, yi, txt, va="center", ha="left",
             color=INK_PRIMARY, fontsize=10, fontweight="medium")

ax.set_yticks(y4)
ax.set_yticklabels(labels4, fontsize=9.5, color=INK_PRIMARY)
ax.set_xscale("log")
ax.set_xlim(10, 20000)
ax.set_xlabel("Temps d'exécution (millisecondes, échelle logarithmique) — scénario medium",
               fontsize=9.5, color=INK_SECONDARY)
ax.xaxis.grid(True, which="major", color=GRIDLINE, linewidth=1, zorder=0)
ax.set_axisbelow(True)
for spine in ["top", "right", "left"]:
    ax.spines[spine].set_visible(False)
ax.spines["bottom"].set_color(BASELINE)
ax.tick_params(axis="x", labelsize=9, colors=INK_MUTED)
ax.tick_params(axis="y", length=0)

legend_handles4 = [
    plt.Rectangle((0, 0), 1, 1, color=BLUE, label="Non corrigé"),
    plt.Rectangle((0, 0), 1, 1, color=AQUA, label="Corrigé"),
]
ax.legend(handles=legend_handles4, loc="lower right", frameon=False,
          fontsize=9.5, labelcolor=INK_SECONDARY)

fig.tight_layout()
fig.savefig("all_engines.png", bbox_inches="tight")
plt.close(fig)

print("OK: results.png, allocations.png, all_engines.png")
